### ISSUE TITLE
supported dongles

### ISSUE THREAD

**Issue by elypter** [ykeara/SteamVR-Dongle-Flash#1]
i recently bought one of these: https://www.ebay.de/itm/Steam-Controller-Wireless-Receiver-USB-dongle-Adapter-For-Steam-game-Controller/303278731314?hash=item469cd23032:g:BLkAAOSwkRhdT34c

however it doesnt work. i am also looking at this reciever

https://www.ebay.de/itm/nRF24LU1-2-4GHz-1mW-USB-Wireless-Daten-Transceiver-Module-94dBm-100m/152699998304?hash=item238da11060:g:DvAAAOSwBG1ZlUtJ

that one also has a LU1P soc on it just like the one you suggest. it is however not exactly the same model. it is a nRFLU1P16 while the suggested dongle has a nRF24LU1. i cannot find a list of all the variants and their specifications however it could be that the nRFLU1P16 only has 16k of rom. would that be enough and are images for different rom sizes even compatible?

**Comment by Benik3** [comment]
Yes, original has 24LU1P which is 32k rom. Not sure if it's compatible.  
Marking is in the datasheet:
![obrazek](https://user-images.githubusercontent.com/4532647/78990028-9b776e00-7b35-11ea-8820-729bab2a03ed.png)

**Comment by ykeara** [comment]
yea  need the 32 kb version,  the Fw is ~18 kb last time I looked.
